CREATE SEQUENCE formapagto_seq
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE gastos_seq
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE cartao_seq
    INCREMENT BY 1
    START WITH 1;

CREATE SEQUENCE grupo_seq
    INCREMENT BY 1
    START WITH 1;